# Generated by Django 5.1.1 on 2024-09-05 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=100)),
                ('nome_social', models.CharField(blank=True, max_length=100, null=True)),
                ('profissao', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField()),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='consultas.profissional')),
            ],
        ),
    ]
